name: expensetracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  expressions: ^0.2.5+1
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.7
  video_player: ^2.9.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/user_image.jpg
    - assets/images/money.jpg
    - assets/images/goal.png
    - assets/images/budget.png
    - assets/videos/intro_video.mp4
    - assets/images/money.png
    - assets/images/sign.png
    - assets/images/logo.jpg
